---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: disable
  hyphens:
    level: warning
  indentation:
    level: error
    spaces: consistent
    indent-sequences: true
  line-length: disable
  truthy: disable

ignore: |
  # Ignore specific files
  # services/kyverno/source/service/**
  **/.tmpl/**
  # .github/workflows/
