name: Validate Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Get changed files
        id: changed
        run: |
          git fetch origin ${{ github.base_ref }}
          # git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt
          git diff --name-only --diff-filter=AM origin/${{ github.base_ref }}...${{ github.sha }} > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Run yamllint on changed YAML files
        run: |
          # grep '\.ya\?ml$' changed_files.txt | grep -v '^.*templates/.*' > changed-yaml.txt || true
          grep '\.ya\?ml$' changed_files.txt \
            | grep -vE '^.*templates/.*|Chart\.yaml$|values\.yaml$' \
            > changed-yaml.txt || true
          cat changed-yaml.txt
          if [ -s changed-yaml.txt ]; then
            echo "Linting regular YAML files..."
            # yamllint -f github $(cat changed-yaml.txt)
            yamllint -c .yamllint-config.yaml $(cat changed-yaml.txt)
          else
            echo "No regular YAML files to lint."
          fi

      - name: Find changed Helm charts
        run: |
          grep -E '(Chart\.yaml|values\.yaml)' changed_files.txt | xargs -I{} dirname {} | sort -u > changed-charts.txt || true
          grep 'templates/' changed_files.txt | sed -E 's|/templates/.*||' | sort -u > temp.txt || true
          # grep -E '(Chart\.yaml|values\.yaml|templates/)' changed_files.txt | sed -E 's|/templates/.*||' | xargs -I{} dirname {} | sort -u > changed-charts.txt || true
          echo "Detected Helm charts:"
          cat changed-charts.txt temp.txt|| echo "None found"

      - name: Run helm
        run: |
          if [ -s changed-charts.txt ]; then
            while IFS= read -r chart_dir; do
              echo "Rendering chart: $chart_dir"
              helm lint "$chart_dir"
            done < changed-charts.txt
          else
            echo "No Helm charts changed."
          fi

      - name: Run helmlint for template/ file
        run: |
          if [ -s temp.txt ]; then
            while IFS= read -r chart_dir; do
              echo "Rendering template chart: $chart_dir"
              helm lint "$chart_dir"
            done < temp.txt
          else
            echo "No Helm charts changed."
          fi
          
      - name: Show current user and home directory
        run: |
          echo "User: $(whoami)"
          echo "HOME: $HOME"
